declare module '*.jpg';
declare module '*.jpeg';
declare module '*.png';
declare module '*.gif';
declare module '*.svg';
declare module '*.webp';
declare module '*.ico';
declare module '@commercetools/sdk-auth';
declare module '*.mjs';
